[palette]
Red = "#ff5555"
Green = "#50fa7b"
Blue = "#6272a4"
Yellow = "#f1fa8c"
Cyan = "#8be9fd"
Magenta = "#ff79c6"
Gray = "#f8f8f2"
White = "#f8f8f2"

[keyword]
fg = "#ff79c6"

[function]
fg = "#50fa7b"

[string]
fg = "#f1fa8c"

[comment]
fg = "#6272a4"

[variable]
fg = "#f8f8f2"

[type]
fg = "#8be9fd"

[operator]
fg = "#ff79c6"

[punctuation.bracket]
fg = "#f8f8f2"

[string.regex]
fg = "#ff5555"
