[palette]
Red = "#fb4934"
Green = "#b8bb26"
Blue = "#83a598"
Yellow = "#fabd2f"
Cyan = "#8ec07c"
Magenta = "#d3869b"
Gray = "#504945"
White = "#ebdbb2"

[keyword]
fg = "#fe8019"

[function]
fg = "#8ec07c"

[type]
fg = "#fabd2f"

[string]
fg = "#b8bb26"

[comment]
fg = "#928374"

[variable]
fg = "#ebdbb2"

[operator]
fg = "#fe8019"

[punctuation.bracket]
fg = "#d5c4a1"

[constant.numeric.integer]
fg = "#d3869b"

[constant.numeric.float]
fg = "#d3869b"
