[palette]
Red = "#f92672"
Green = "#a6e22e"
Blue = "#61afef"
Yellow = "#e6db74"
Cyan = "#66d9ef"
Magenta = "#c678dd"
Gray = "#495162"
White = "#f8f8f2"

[keyword]
fg = "#ff79c6"

[function]
fg = "#50fa7b"

[type]
fg = "#ff79c6"

[string]
fg = "#f1fa8c"

[comment]
fg = "#6272a4"

[variable]
fg = "#f8f8f2"

[operator]
fg = "#ff79c6"

[punctuation.bracket]
fg = "#495162"

[constant.numeric.integer]
fg = "#bd93f9"

[constant.numeric.float]
fg = "#bd93f9"
