[palette]
Red = "#f92672"
Green = "#a6e22e"
Blue = "#66d9ef"
Yellow = "#e6db74"
Cyan = "#a1efe4"
Magenta = "#fd971f"
Purple = "#ae81ff"
Gray = "#75715e"
White = "#f8f8f2"
Orange = "#fd971f"

[keyword]
fg = "#f92672"

[function]
fg = "#a6e22e"

[string]
fg = "#e6db74"

[comment]
fg = "#75715e"

[variable]
fg = "#f8f8f2"

[type]
fg = "#66d9ef"

[operator]
fg = "#f92672"

[punctuation.bracket]
fg = "#f8f8f2"

[constant.builtin]
fg = "#ae81ff"

[constant.numeric]
fg = "#ae81ff"

[string.regex]
fg = "#ce9178"

[type.builtin]
fg = "#66d9ef"
